/**:
    ros__parameters:
        robot_description_planning:
# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
            default_velocity_scaling_factor: 0.1
            default_acceleration_scaling_factor: 0.1

            # Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
            # Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
            joint_limits:
              joint_arm_l0:
                has_velocity_limits: true
                max_velocity: 0.14
                has_acceleration_limits: true
                max_acceleration: 0.14
              joint_arm_l1:
                has_velocity_limits: true
                max_velocity: 0.14
                has_acceleration_limits: true
                max_acceleration: 0.14
              joint_arm_l2:
                has_velocity_limits: true
                max_velocity: 0.14
                has_acceleration_limits: true
                max_acceleration: 0.14
              joint_arm_l3:
                has_velocity_limits: true
                max_velocity: 0.14
                has_acceleration_limits: true
                max_acceleration: 0.14
              joint_gripper_finger_left:
                has_velocity_limits: true
                max_velocity: 4.0
                has_acceleration_limits: true
                max_acceleration: 10.0
              joint_gripper_finger_right:
                has_velocity_limits: true
                max_velocity: 4.0
                has_acceleration_limits: true
                max_acceleration: 10.0
              joint_head_pan:
                has_acceleration_limits: true
                has_velocity_limits: true
                max_acceleration: 8.0
                max_velocity: 3.0
              joint_head_tilt:
                has_acceleration_limits: true
                has_velocity_limits: true
                max_acceleration: 8.0
                max_velocity: 3.0
              joint_lift:
                has_velocity_limits: true
                max_velocity: 0.15
                has_acceleration_limits: true
                max_acceleration: 0.095
              joint_wrist_yaw:
                has_velocity_limits: true
                max_velocity: 3.0
                has_acceleration_limits: true
                max_acceleration: 8.0
              position/x:
                has_velocity_limits: true
                max_velocity: 0.15
                has_acceleration_limits: true
                max_acceleration: 0.2
              position/y:
                has_velocity_limits: true
                max_velocity: 0.15
                has_acceleration_limits: true
                max_acceleration: 0.2
              position/theta:
                has_velocity_limits: true
                max_velocity: 0.05
                has_acceleration_limits: true
                max_acceleration: 0.05
